/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

  // By default, Docusaurus generates a sidebar from the docs folder structure

  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  docsSidebar: [

    {
      type: 'category',
      label: 'Introduction',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'introduction/0',
        },
        {
          type: 'doc',
          id: 'introduction/1',
        },
        {
          type: 'doc',
          id: 'introduction/2',
        },
      ],
    },
    {
      type: 'category',
      label: 'Inery Wallet Guide',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'inery-wallet-guide/0',
        },
        {
          type: 'doc',
          id: 'inery-wallet-guide/1',
        },
        {
          type: 'doc',
          id: 'inery-wallet-guide/2',
        },
        {
          type: 'doc',
          id: 'inery-wallet-guide/3',
        },
        {
          type: 'doc',
          id: 'inery-wallet-guide/4',
        },
        {
          type: 'doc',
          id: 'inery-wallet-guide/5',
        },
      ],
    },
    {
      type: 'category',
      label: 'Becoming a Lite Node',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'becoming-a-lite-node/0',
        },
        {
          type: 'doc',
          id: 'becoming-a-lite-node/1',
        },
        {
          type: 'doc',
          id: 'becoming-a-lite-node/2',
        },
      ],
    },
    {
      type: 'category',
      label: 'Becoming a Master Node',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'becoming-a-master-node/0',
        },
        {
          type: 'doc',
          id: 'becoming-a-master-node/1',
        },
        {
          type: 'doc',
          id: 'becoming-a-master-node/2',
        },
      ],
    },
    {
      type: 'category',
      label: 'Command Line',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'command-line/0',
        },
      ],
    },
  ],
};

module.exports = sidebars;
